### ISSUE TITLE
err

### ISSUE THREAD

**Issue by AutschHa** [moyada/stealer#86]
[root@k8s-node5 ~]# docker logs 6672c9ad9c7b
Watching for file changes with StatReloader
[INFO][2023-04-11 22:07:40,701][autoreload.py:637]Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
April 11, 2023 - 22:07:40
Django version 3.2.18, using settings 'stealer.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[11/Apr/2023 22:07:56] "GET / HTTP/1.1" 200 638
[11/Apr/2023 22:07:56] "GET /static/js/manifest.2ae2e69a05c33dfc65f8.js HTTP/1.1" 200 857
[11/Apr/2023 22:07:56] "GET /static/js/app.b1580297df35fe4dd0fb.js HTTP/1.1" 200 8914
[11/Apr/2023 22:07:56] "GET /static/css/app.4188e923994bfdb7fc8221bd72a8a5f9.css HTTP/1.1" 200 241564
[11/Apr/2023 22:07:57] "GET /static/js/vendor.e4fa7f252e45c6d3ca11.js HTTP/1.1" 200 939253
[11/Apr/2023 22:07:57] "GET /static/img/logo.dc93bc7.png HTTP/1.1" 200 47972
[11/Apr/2023 22:07:57] "GET /static/fonts/element-icons.535877f.woff HTTP/1.1" 200 28200
Not Found: /favicon.ico
[WARNING][2023-04-11 22:07:57,408][log.py:230]Not Found: /favicon.ico
[11/Apr/2023 22:07:57] "GET /favicon.ico HTTP/1.1" 404 2343
[11/Apr/2023 22:07:57] "GET /static/favicon.ico HTTP/1.1" 200 7219
[INFO][2023-04-11 22:09:12,456][controller.py:31]get douyin video info ==> https://v.douyin.com/Avr3Bpf.
[DEBUG][2023-04-11 22:09:12,460][connectionpool.py:1007]Starting new HTTPS connection (1): v.douyin.com:443
[DEBUG][2023-04-11 22:09:12,554][connectionpool.py:465]https://v.douyin.com:443 "GET /Avr3Bpf HTTP/1.1" 302 358
[DEBUG][2023-04-11 22:09:12,556][connectionpool.py:1007]Starting new HTTPS connection (1): www.iesdouyin.com:443
[DEBUG][2023-04-11 22:09:12,632][connectionpool.py:465]https://www.iesdouyin.com:443 "GET /share/video/7212918206074309899/?region=CN&mid=7199918425762335546&u_code=0&did=MS4wLjABAAAAg7fuuuOV7SlhjO-EnMaKX7xPL2mDy0SLBn2fer9kOrY6qVhxLD-72lg5uDn2dHm4&iid=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yYlXQnRwQQ&with_sec_did=1&titleType=title&from_ssr=1&from=web_code_link HTTP/1.1" 200 None
[DEBUG][2023-04-11 22:09:12,645][connectionpool.py:1007]Starting new HTTPS connection (1): www.douyin.com:443
[DEBUG][2023-04-11 22:09:12,849][connectionpool.py:465]https://www.douyin.com:443 "GET /video/7212918206074309899?previous_page=app_code_link HTTP/1.1" 200 None
[11/Apr/2023 22:09:13] "GET /video/info?url=0.02%20qEu:/%20%E7%BC%A0%E4%BD%8F%E5%90%BB%E4%BD%8F%E6%98%A5%E9%A3%8E%E5%90%B9%E4%BD%8F%E6%88%91%E5%90%97%20%E6%98%A5%E9%A3%8E%E5%90%B9%E4%BD%8F%E4%BA%86%E6%85%A2%E5%8A%A8%E4%BD%9C%20%20https://v.douyin.com/Avr3Bpf/%20%E5%A4%8D%E5%88%B6%E6%AD%A4%E9%93%BE%E6%8E%A5%EF%BC%8C%E6%89%93%E5%BC%80Dou%E9%9F%B3%E6%90%9C%E7%B4%A2%EF%BC%8C%E7%9B%B4%E6%8E%A5%E8%A7%82%E7%9C%8B%E8%A7%86%E9%A2%91%EF%BC%81 HTTP/1.1" 200 456
[INFO][2023-04-11 22:09:15,686][controller.py:58]download douyin ==> 缠住吻住春风吹住我吗#春风吹住了慢动作.
Internal Server Error: /video/download
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/route/controller.py", line 59, in download_file
    return vid_download.download(info)
  File "/code/core/vid_download.py", line 20, in download
    file = store.find_file(info.platform, info.filename)
  File "/code/tools/store.py", line 30, in find_file
    filename = make_path(vtype.value, filename)
  File "/code/tools/store.py", line 25, in make_path
    os.mkdir(path)
FileNotFoundError: [Errno 2] No such file or directory: 'video/douyin'
[ERROR][2023-04-11 22:09:15,750][log.py:230]Internal Server Error: /video/download
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/route/controller.py", line 59, in download_file
    return vid_download.download(info)
  File "/code/core/vid_download.py", line 20, in download
    file = store.find_file(info.platform, info.filename)
  File "/code/tools/store.py", line 30, in find_file
    filename = make_path(vtype.value, filename)
  File "/code/tools/store.py", line 25, in make_path
    os.mkdir(path)
FileNotFoundError: [Errno 2] No such file or directory: 'video/douyin'
[11/Apr/2023 22:09:15] "GET /video/download?token=douyinbad68c2f088d773d37815a33787d9616 HTTP/1.1" 500 72029

**Comment by aslanTT** [comment]
+ 1

**Comment by moyada** [comment]
改好了，自动创建
