### ISSUE TITLE
皮皮虾链接解析失败

### ISSUE THREAD

**Issue by pedoc** [moyada/stealer#90]
测试链接
https://h5.pipix.com/s/UCq8oeu/

控制太台输出
```
Watching for file changes with StatReloader
[INFO][2023-06-03 11:23:19,852][autoreload.py:668]Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
June 03, 2023 - 11:23:19
Django version 4.2.1, using settings 'stealer.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

[03/Jun/2023 11:23:28] "GET / HTTP/1.1" 200 638
[03/Jun/2023 11:23:28] "GET /static/css/app.4188e923994bfdb7fc8221bd72a8a5f9.css HTTP/1.1" 304 0
[03/Jun/2023 11:23:28] "GET /static/js/manifest.2ae2e69a05c33dfc65f8.js HTTP/1.1" 304 0
[03/Jun/2023 11:23:28] "GET /static/js/vendor.e4fa7f252e45c6d3ca11.js HTTP/1.1" 304 0
[03/Jun/2023 11:23:28] "GET /static/js/app.b1580297df35fe4dd0fb.js HTTP/1.1" 304 0
[03/Jun/2023 11:23:28] "GET /static/img/logo.dc93bc7.png HTTP/1.1" 304 0
[03/Jun/2023 11:23:28] "GET /static/fonts/element-icons.535877f.woff HTTP/1.1" 304 0
[03/Jun/2023 11:23:31] "GET /static/css/app.4188e923994bfdb7fc8221bd72a8a5f9.css.map HTTP/1.1" 200 342851
[INFO][2023-06-03 11:23:36,902][controller.py:31]get pipixia video info ==> https://h5.pipix.com/s/UCq8oeu.
Internal Server Error: /video/info
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\OpenSource\stealer\route\controller.py", line 36, in get_info
    if result.is_success():
       ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_success'
[ERROR][2023-06-03 11:23:36,936][log.py:241]Internal Server Error: /video/info
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\OpenSource\stealer\route\controller.py", line 36, in get_info
    if result.is_success():
       ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_success'
[03/Jun/2023 11:23:36] "GET /video/info?url=https://h5.pipix.com/s/UCq8oeu/ HTTP/1.1" 500 76666
```

web上会弹出html内容 
![image](https://github.com/moyada/stealer/assets/6604230/4a6b2dd8-f14d-4812-a191-f289890ff8c3)

感谢

**Comment by pedoc** [comment]
已自行解决 https://github.com/pedoc/fwm
